### ISSUE TITLE
Fit direction into map

### ISSUE THREAD

**Issue by vuphuctho** [bramus/react-native-maps-directions#14] opened 2018-01-31 11:34 UTC
I need `MapView` to zoom and display the direction fully in screen. Is there anyway to let `MapView` knows the boundary of rendered direction to fit it into map?

**Comment by bramus** [comment] 2018-01-31 21:51
Duplicate of https://github.com/bramus/react-native-maps-directions/issues/2

**Closed by bramus** 2018-01-31 21:51 UTC
