### ISSUE TITLE
Get directions Android Physical device

### ISSUE THREAD

**Issue by janvdt** [bramus/react-native-maps-directions#19] opened 2018-02-19 12:12 UTC
When trying to get directions between 2 points i seem to get a response from Google Directions API. But my console logs this error

--------- beginning of crash 02-16 12:07:46.385 10186-10186/? E/AndroidRuntime: FATAL EXCEPTION: main Process: com.Paxi, PID: 10186 com.facebook.react.bridge.UnexpectedNativeTypeException: Tried to read an int, but got a non-integral double: 20.571429

Any idea on this? this is when running on android physical device

**Comment by bramus** [comment] 2018-02-19 12:18
I have an app in the Play Store with `react-native-maps-directions` and it runs just fine on Android …

Could you detail which versions of the following are you using:
- Android
- React Native
- `react-native-maps`
- `react-native-maps-directions`

**Comment by 8Ozymandias** [comment] 2018-03-07 09:37
@bramus For that app you have in the app store that is able to make use of the react-native-maps-directions, what version of Android, React Native and react-native-maps and react-native-maps-directions did you utilize in order to make it work?

**Comment by bramus** [comment] 2018-03-07 13:50
@janvdt Can you provide some more info on this? Otherwise I'm going to close this issue as there's not enough info for me to work with.

**Comment by bramus** [comment] 2018-03-07 13:56
@8Ozymandias `react-native-maps-directions` has been tested with `react-native-maps` 0.16 and higher. That version of `react-native-maps` is compatible with `react-native` 0.47.0 or higher.

Do note that `react-native-maps` 0.20.1 is **not compatible** with the newly released `react-native` 0.54.0. A hotfix has landed in their master though _(See https://github.com/react-community/react-native-maps/pull/2053)_

**Comment by bramus** [comment] 2018-03-29 19:13
Closing due to inactivity / insufficient information.

Feel free to add some more info and I'll gladly reopen.

**Closed by bramus** 2018-03-29 19:13 UTC
Labels: more info needed

**Comment by yogeshmoradiya121** [comment] 2018-04-18 09:58
this issue happen in android kit kat 4.4.2 can anyone solve this??

**Comment by MariamMobeen** [comment] 2018-06-21 13:48
I get this issue in  Android version 7.1. Did you find the solution for it?

**Comment by nomoreboredom** [comment] 2019-02-13 09:26
react-native-maps version 0.20.1, react-native v 0.53.3, android api23, react-native-maps-directions 1.6 the same as above

**Comment by nomoreboredom** [comment] 2019-02-13 10:53
Which is only occurring if edgePadding is used on onReady for fitToCoordinates function, fyi

**Comment by bramus** [comment] 2019-02-13 11:16
Thanks for the extra info @nomoreboredom. 

Can you provide a full example somewhere (a gist or repo) in which the issue can be reproduced? That way I can help pinpointing the source of the problem.

**Comment by nomoreboredom** [comment] 2019-02-13 11:26
Sorry man, private repo but I was getting Screen Width using sth like Dimensions.width / 30, and if this number results in a decimal number, edgePadding was throwing error. Applying Math.floor fixed the issue for me

**Comment by bramus** [comment] 2019-02-13 11:44
Looks like it’s a problem with `react-native-maps` itself then. As the error mentions: it requires an int somehwere, but receives a double.

**Comment by SevdaCimen** [comment] 2019-03-20 13:36
> Sorry man, private repo but I was getting Screen Width and was using sth like Dimensions.width / 30, and if this number results in a decimal number, edgePadding was throwing error. Applying Math.floor fixed the issue for me

yes thats works on me !thanks
