### ISSUE TITLE
Cannot set property 'map' of undefined

### ISSUE THREAD

**Issue by duongkhoangiam** [bramus/react-native-maps-directions#132] opened 2020-03-17 09:08 UTC
I am using lastest expo and react native got this error !

**Comment by bramus** [comment] 2020-03-17 09:23
Thanks for reporting. Duplicate of #130 and #131 . I'll track this further in #130.

**Closed by bramus** 2020-03-17 09:23 UTC

**Comment by bramus** [comment] 2020-03-17 10:00
Version 1.7.5 with a fix for this got released. Thanks for the input.

**Comment by duongkhoangiam** [comment] 2020-03-17 12:00
Thanks you for fast update , after update Cannot set property 'map' of undefined is solved but i got new problem
Unhandled promise rejection, [TypeError: Cannot read property 'distance' of undefined]

**Comment by bramus** [comment] 2020-03-17 13:00
This is a new, separate, problem. I've tracked it down to using a wrong/wrongly configured API Key, or when a route request does not succeed for some reason.

You should see another error triggered just before the `TypeError: Cannot read property 'distance' of undefined` error, describing what went wrong. Either way: I've pushed a change to `master` which improves error handling, so that only that the code stops after the first error. Could you try that version out?

You can test this version in `master` by referring to the repository directly instead of going through the npm registry. See https://www.bram.us/2019/12/09/use-a-github-repository-as-a-dependency-in-package-json/ for instructions.

**Comment by duongkhoangiam** [comment] 2020-03-17 15:06
You are correct , the problem because my API key is not allow 
Now good working. Good jobs bro. and many Thanks !

**Comment by duongkhoangiam** [comment] 2020-03-17 15:15
I think you need error triggered when fetch response with error API key now allow is good 
Thanks you
