### ISSUE TITLE
New feature: Animated directions/polyline

### ISSUE THREAD

**Issue by jakelacey2012** [bramus/react-native-maps-directions#42] opened 2018-05-03 21:07 UTC
Thanks for taking the time to put this library together saved me a ton!

I wish to add additional functionality to this library to allow the drawing of the directions to be animated. Let me know if you would be willing to accept this change.

**Comment by bramus** [comment] 2018-05-03 21:10
Duplicate of #34.

Please see the answer provided at the linked issue: this will need to be added in `react-native-maps`, not `react-native-maps-directions`.

**Closed by bramus** 2018-05-03 21:10 UTC
